#cloud-config
rancher:
runcmd:
  - wget https://github.com/lithium/quake3-slugfest/archive/master.zip -O /home/rancher/slugfest.zip
  - unzip /home/rancher/slugfest.zip -d /home/rancher
write_files:
  - path: /home/rancher/start-all
    permissions: "0755"
    owner: rancher
    content: |
      #!/bin/bash
      /home/rancher/start-quake3
      /home/rancher/start-slugfest
  - path: /home/rancher/start-quake3
    permissions: "0755"
    owner: rancher
    content: |
      #!/bin/bash
      docker run --name quake3 -d -p 0.0.0.0:27960:27960/udp \
      -v /home/rancher/quake3/baseq3/pak0.pk3:/pak0.pk3 \
      jberrenberg/quake3 +rconpassword rueB1ks +map q3dm17
  - path: /home/rancher/start-slugfest
    permissions: "0755"
    owner: rancher
    content: |
      #!/bin/bash
      docker run --name slugfest -d -p 0.0.0.0:42000:27960/udp \
      -v /home/rancher/quake3/baseq3/pak0.pk3:/pak0.pk3 \
      -v /home/rancher/quake3-slugfest-master:/home/ioq3srv/.q3a/slugfest \
      jberrenberg/quake3 +rconpassword rueB1ks +map q3dm17 +set fs_game slugfest
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      /home/rancher/start-all
